name: CollabVM Server

on: [push, pull_request]

jobs:
  ubuntu_x64: # Latest version of Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [{"type": "PNG", "makeopts": "", "extdeps": ""},{"type": "JPEG", "makeopts": "JPEG=1", "extdeps": ""},{"type": "PNG-UPnP", "makeopts": "UPNP=1", "extdeps": "libminiupnpc-dev"},{"type": "JPEG-UPnP", "makeopts": "JPEG=1 UPNP=1", "extdeps": "libminiupnpc-dev"}]
    steps:
      - uses: actions/checkout@main
        with: 
          submodules: true
      - name: Install Dependencies
        id: depends
        run: | 
          sudo apt update
          sudo ./scripts/grab_deps_linux.sh
      - name: Install Extra Dependencies
        id: extdepends
        if: ${{matrix.flavor.extdeps != ''}}
        run: | 
          sudo apt install ${{matrix.flavor.extdeps}}
      - name: Install latest LLVM/Clang
        id: llvm
        run: |
          # We need the latest version of Clang to build the server.
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 13
      - name: Build
        id: build
        run: |
          # Use clang instead of GCC
          make ${{matrix.flavor.makeopts}} CC=clang-13 CXX=clang++-13 -j$(nproc)
      - name: Upload Artifact - PNG
        uses: actions/upload-artifact@v2
        with: 
          name: server_binary-${{matrix.flavor.type}}
          path: './bin/**/*'